apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-latest
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-app
      version: latest
  template:
    metadata:
      labels:
        app: web-app
        version: latest
    spec:
      containers:
      - name: web-app-container
        image: eywrld839/webapp:arg
        env:
          - name: COLOR
            value: "$COLOR"
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: web-app
